name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Webhook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_dhV74BOZMN9D2Jewkqv7k13zBhSj/m9p6JBP6v3
